name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: Lint project files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint
